const GET_COUNTRIES = 'GET_COUNTRIES';
const GET_COUNTRY = 'GET_COUNTRY';
const DELETE_COUNTRY = 'DELETE_COUNTRY';
const SEARCH_COUNTRIES = 'SEARCH_COUNTRIES';
const SET_CONTINENT = 'SET_CONTINENT';

export {GET_COUNTRIES, GET_COUNTRY, DELETE_COUNTRY, SEARCH_COUNTRIES, SET_CONTINENT};
